import type { AgentCategory, AgentEdge, AgentPresentationDef } from './agentControlCenter.types'

export const AGENT_CARDS: AgentPresentationDef[] = [
  {
    key: 'strategist',
    promptId: 'strategist-agent-prompt',
    name: 'Strategist / Стратег',
    icon: '📊',
    category: 'marketing',
    desc: 'Бізнес-модель, аватар, конкуренти, офер і позиціонування.',
    isSystem: true,
    sourceFiles: ['docs/agents/ai-strategist/business-model-full.md', 'docs/agents/ai-strategist/competitor-analysis.md'],
  },
  {
    key: 'content',
    promptId: 'content-agent-prompt',
    name: 'Генератор контенту (DNA)',
    icon: '🎬',
    category: 'marketing',
    desc: 'Рілси й банери у ДНК-тоні бренду.',
    isSystem: true,
    sourceFiles: ['docs/agents/ai-content/SKILL-creative-ads.md', 'docs/agents/ai-content/dna-content-generator-offer.md'],
  },
  {
    key: 'trend_radar',
    promptId: 'trend-radar-prompt',
    name: 'Тренд-радар',
    icon: '📈',
    category: 'marketing',
    desc: 'Тренди Reels / TikTok у реальному часі.',
    isSystem: false,
    sourceFiles: ['docs/agents/ai-content/SKILL-output-engine.md'],
  },
  {
    key: 'assistant',
    promptId: 'assistant-agent-prompt',
    name: 'TG / IG Асистент',
    icon: '💬',
    category: 'sales',
    desc: 'Веде діалог із лідами, guardrails-шар.',
    isSystem: true,
    sourceFiles: ['docs/agents/ai-assistant-bot/00-SURGICAL-SYSTEM-UPDATE.md', 'docs/agents/ai-assistant-bot/ANALYSIS-strict-guardrails.md'],
  },
  {
    key: 'sales',
    promptId: 'sales-agent-prompt',
    name: 'AI-Seller',
    icon: '🎯',
    category: 'sales',
    desc: 'SPIN-продажі, закриває заперечення.',
    isSystem: true,
    sourceFiles: ['docs/agents/ai-seller/ai-seller-system-prompt.md', 'docs/agents/ai-seller/ai-seller-rules.md'],
  },
  {
    key: 'funnel',
    promptId: 'funnel-agent-prompt',
    name: 'Воронка (Funnel agent)',
    icon: '📄',
    category: 'sales',
    desc: 'Рух по воронці, конверсія, drop-off аналіз.',
    isSystem: true,
    sourceFiles: ['docs/agents/ai-funnel-assistant/README.md'],
  },
  {
    key: 'mentor',
    promptId: 'mentor-agent-prompt',
    name: 'AI-Mentor (ABSystem)',
    icon: '🧭',
    category: 'ops',
    desc: 'Щоденний цикл, колесо балансу, comeback-flow.',
    isSystem: true,
    sourceFiles: ['docs/agents/ai-mentor/methodology-absystem.md', 'docs/agents/ai-mentor/comeback-flows.md'],
  },
  {
    key: 'zoom_recap',
    promptId: 'zoom-recap-prompt',
    name: 'Zoom-розбори',
    icon: '📝',
    category: 'ops',
    desc: 'Задачі й підсумки після групових Zoom.',
    isSystem: false,
    sourceFiles: ['docs/agents/ai-mentor/focus-course-materials.md'],
  },
  {
    key: 'coach',
    promptId: 'coach-agent-prompt',
    name: 'База знань / Coach-OS',
    icon: '🗂️',
    category: 'ops',
    desc: 'Памʼять і профіль кожного учасника ФОКУСУ.',
    isSystem: true,
    sourceFiles: ['docs/agents/shared/OPERATING-RULES.md', 'docs/client/svoia-nadya/SKILL-coach.md'],
  },
]

export const AGENT_EDGES: AgentEdge[] = [
  { from: 'trend_radar', to: 'content', label: 'тренди' },
  { from: 'content', to: 'assistant', label: 'контент' },
  { from: 'assistant', to: 'sales', label: 'лід' },
  { from: 'sales', to: 'mentor', label: 'після купівлі' },
  { from: 'mentor', to: 'zoom_recap', label: 'після Zoom' },
  { from: 'zoom_recap', to: 'coach', label: 'підсумки' },
]

export const CATEGORY_META: Record<AgentCategory, { label: string; icon: string; color: string }> = {
  marketing: { label: 'Маркетинг і трафік', icon: '📡', color: '#38c6ff' },
  sales: { label: 'Продажі й клієнти', icon: '🤝', color: '#ff9a3d' },
  ops: { label: 'Операції й продуктивність', icon: '⚙️', color: '#b370ff' },
}
