packages:
  - 'backend'
  - 'apps/*'
  - 'packages/*'
  - 'video-hooks'
onlyBuiltDependencies:
  - "@prisma/client"
  - "@prisma/engines"
  - "prisma"
  - "esbuild"
  - "@parcel/watcher"
  - "core-js"
  - "msgpackr-extract"