packages:
  - "apps/*"
  - "backend"
  - "packages/*"
  - "video-hooks"

onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@prisma/client"
  - "@prisma/engines"
  - "core-js"
  - "esbuild"
  - "msgpackr-extract"
  - "prisma"