packages:
  - "apps/*"
  - "backend"
  - "packages/*"
  - "video-hooks"
allowBuilds:
  '@parcel/watcher': true
  '@prisma/client': true
  '@prisma/engines': true
  core-js: true
  esbuild: true
  msgpackr-extract: true
  prisma: true
