// frontend/src/shared/types/tagTypes.ts
export const TAG_TYPES = [
  'User',
  'Users',
  'Funnel',
  'Product',   'Products',
  'Module',
  'Lesson',
  'Task',
  'Quiz',
  'Analytics',
  'Achievement',
  'Level',
  'UserProgress',
  'Completion',
  'Social',
  'Payment',
  'Notification',
  'Message',
  'Media',
  'Review',
  'Support',
  'Stats',
  'Chat',
  'Wheel',
  'WheelHistory',
  'DailySessions',
  'UserMetrics',
  'Vision',
  'Goals',
  'Actions',
  'DecisionChecks',
  'OnboardingStatus',
  'Mirrors',
  'TrialStatus',
  'MiniCourses',
  'Consultations',
  'ZoomSessions',
  'TelegramUser',
  'TelegramMessages',
  'MiniApp',
  'Subscription',
  'Achievements',
  'UserLevel',
  'CronConfig',
  'MentorSetup',
  'Mentor',
  'Session',
  'Progress',
  'Ownership',
  'AssistantProgress',
  'AdminProgress',
  'Recommendations',

  'Questions',
  'Answers',
  'Courses',

  'AI',
  'AIMentor',
  'MicroTasks',
  'AIPrompt',
  'AITemplate',
  'AIAnalysis',
  'Members',
  'WheelCooldown',
  'WheelAnalysis',
  'Rating',
  'Access',
  'MentorAccess', 'Onboarding',
  'AdminSettings',
  'AdminProducts',
  'PromptVersions',
  'Daily', 'DailyCycle', 'Streak',
  'Trial',
  'Mirror',
  'Consultation',
  'Theme',
  'Avatar',
  'Pricing',
  'Coupon',
  'Transaction',
  'Invoice',
  'Refund',
  'WhiteLabel',
  'FAQ',
  'Template',
  'Blueprint',
  'Reward', 'Points', 'GamificationProfile',
  'Challenge',
  'Leaderboard',
  'AdminProducts',
  'Comment',
  'Quota',
  'Generation',
  'WeeklyReport',
  'MentorProfile',
  'MentorContext',
'ZoomSession', 
'ZoomAttendee', 
'Journal',
  'WebMap',
  'WebMapDailyQuestion',
] as const

export type TagType = (typeof TAG_TYPES)[number]
