export enum NotificationEvent {
  DAILY_MORNING_DUE = 'DAILY_MORNING_DUE',
  DAILY_EVENING_DUE = 'DAILY_EVENING_DUE',
  STREAK_RISK = 'STREAK_RISK',
  STREAK_MILESTONE = 'STREAK_MILESTONE',
  STREAK_BROKEN = 'STREAK_BROKEN',
  LEVEL_UP = 'LEVEL_UP',
  NEAR_LEVEL_UP = 'NEAR_LEVEL_UP',
  WEEKLY_SUMMARY = 'WEEKLY_SUMMARY',
  AI_INACTIVE = 'AI_INACTIVE',
  SUBSCRIPTION_EXPIRING = 'SUBSCRIPTION_EXPIRING',
}
