export const coachBotContent = {
  start: {
    title: 'Coach OS',
    subtitle: 'Єдиний потік коуча: новий Zoom, бібліотека, аналітика, контент і системні дії.',
  },
  menu: {
    newZoom: '🎙 Новий Zoom',
    audio: '📚 Бібліотека Zoom',
    dna: '📊 Аналітика',
    content: '🎬 Контент',
    system: '⚙️ Система',
    schedule: '📅 Календар Zoom',
    nextWeek: '➕ Schedule add',
    members: '👥 Users',
    notifications: '🔔 Notify',
    planner: '📝 Плануємо контент',
    script: '✏️ Мій сценарій',
    payments: '💳 Payments',
  },
  schedule: {
    title: 'Мій розклад на тиждень',
    slotOpen: '✓',
    slotClosed: '✗',
    toggleOpen: 'Відкрити',
    toggleClose: 'Закрити',
    saved: 'Збережено',
  },
  nextWeek: {
    title: '📅 Наступний тиждень — {dates}',
    intro: 'Всі дні відкриті за замовчуванням.\nЗакрий що не підходить.',
    dayOpen: '✅ {day} {date}',
    dayClosed: '❌ {day} {date}',
    btnHours: '🕐 Налаштувати години',
    btnDone: '✅ Готово',
    saved: '✅ Збережено',
    hoursTitle: 'Години — {day} {date}:',
    hourOpen: '✅ {h}',
    hourClosed: '❌ {h}',
    days: ['Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб', 'Нд'],
    hours: [9, 11, 13, 15, 17, 19],
  },
  analytics: {
    title: 'Analytics',
    total: 'Всього учасників',
    inTest: 'Проходять тест',
    testDone: 'Завершили тест',
    focusPaid: 'Оплатили ФОКУС',
    zoomActive: 'Активні в Zoom',
    conversion: 'Конверсія тест → ФОКУС',
    abSystemUpgrades: 'ABSystem апгрейди',
    revenue: 'Revenue',
    mrr: 'MRR',
    noData: 'Дані ще збираються',
  },
  stats: {
    title: 'Stats',
    newUsers: 'Нові користувачі',
    activeUsers: 'Активні користувачі',
    avgActions: 'Середня активність / юзер',
    streakUsers: 'Користувачі зі streak',
    retention: 'Retention',
    funnel: 'Funnel',
    liveActivity: 'Live activity',
  },
  audio: {
    title: 'Аудіо ЗУМИ ФОКУС',
    listEmpty: 'Поки що Zoom-аудіо не знайдено.',
    listHeader: 'Zoom library',
    ingestStarted: 'Запускаю ручну обробку аудіо...',
    ingestDone: 'Ручну обробку аудіо завершено.',
    uploadPrompt: [
      'Надішли сюди MP3, M4A, WAV або voice-повідомлення.',
      'Далі система сама проведе файл через Cloudinary, транскрипцію, AI-аналіз і збереже Zoom у бібліотеку.',
    ].join('\n\n'),
    usage: '/audio — бібліотека Zoom\n/audio 2026-06 — бібліотека за місяць\n/audio run — ручний Cloudinary ingest',
  },
  system: {
    title: 'Система',
    subtitle: 'Службові дії, які не повинні бути окремими entry point у головному меню.',
  },
  users: {
    title: 'Users',
    listHeader: 'Останні користувачі',
    searchHeader: 'Результати пошуку',
    empty: 'Користувачів не знайдено.',
    usage: '/users — список\n/users search <query> — пошук',
  },
  notify: {
    title: 'Notifications',
    usage: '/notify all <message>\n/notify user <id|email|tgId> <message>',
    done: '✅ Повідомлення відправлено.',
  },
  payments: {
    title: 'Payments',
    noData: 'Поки що даних по платежах немає.',
  },
} as const
