export const coachBotContent = {
  start: {
    title: 'Панель коуча',
    subtitle: 'Оберіть розділ для керування.',
  },
  menu: {
    schedule: 'Мій розклад',
    nextWeek: '📅 Наступний тиждень',
    dna: 'ДНК аналітика',
    members: 'Учасники',
    notifications: 'Нотифікації',
  },
  schedule: {
    title: 'Мій розклад на тиждень',
    slotOpen: '✓',
    slotClosed: '✗',
    toggleOpen: 'Відкрити',
    toggleClose: 'Закрити',
    saved: 'Збережено',
  },
  nextWeek: {
    title: '📅 Наступний тиждень — {dates}',
    intro: 'Всі дні відкриті за замовчуванням.\nЗакрий що не підходить.',
    dayOpen: '✅ {day} {date}',
    dayClosed: '❌ {day} {date}',
    btnHours: '🕐 Налаштувати години',
    btnDone: '✅ Готово',
    saved: '✅ Збережено',
    hoursTitle: 'Години — {day} {date}:',
    hourOpen: '✅ {h}',
    hourClosed: '❌ {h}',
    days: ['Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб', 'Нд'],
    hours: [9, 11, 13, 15, 17, 19],
  },
  analytics: {
    title: 'ДНК аналітика',
    total: 'Всього учасників',
    inTest: 'Проходять тест',
    testDone: 'Завершили тест',
    focusPaid: 'Оплатили ФОКУС',
    zoomActive: 'Активні в Zoom',
    conversion: 'Конверсія тест → ФОКУС',
    noData: 'Дані ще збираються',
  },
} as const
