// frontend/src/shared/types/tagTypes.ts
export const TAG_TYPES = [
  'User',
  'Funnel',
  'Product',
  'Module',
  'Lesson',
  'Task',
  'Quiz',
  'Analytics',
  'Achievement',
  'Level',
  'UserProgress',
  'Completion',
  'Social',
  'Payment',
  'Notification',
  'Message',
  'Media',
  'Review',
  'Support',
  'Stats',
  'Chat',
  'Wheel',
  'WheelHistory',
  'DailySessions',
  'UserMetrics',
  'Vision',
  'Goals',
  'Actions',
  'DecisionChecks',
  'OnboardingStatus',
  'Mirrors',
  'TrialStatus',
  'MiniCourses',
  'Consultations',
  'ZoomSessions',
  'TelegramUser',
  'TelegramMessages',
  'MiniApp',
  'Subscription',
  'Achievements',
  'UserLevel',
  'CronConfig',
  'MentorSetup',
  'Mentor',
  'Session',
  'Progress',
  'Recommendations',

  'Questions',
  'Answers',

  'AI',
  'MicroTasks',
  'AIPrompt',
  'AITemplate',
  'AIAnalysis',
  

] as const

export type TagType = (typeof TAG_TYPES)[number]