import { useContext } from './useContext'
import { useDerived } from './useDerived'
import { useRecovery } from './useRecovery'
import { useMicrotasks } from './useMicrotasks'
import { useRouteSync } from './useRouteSync'
import { useCycleActions } from './useCycleActions'

export function useDashboardState() {
  const context = useContext()
  const derived = useDerived(context)
  const recovery = useRecovery(
    context,
    derived,
  )
  const microtasks = useMicrotasks(
    context,
    derived,
    recovery,
  )

  useRouteSync(
    context,
    derived,
    recovery,
    microtasks,
  )

  const cycleActions = useCycleActions(
    context,
    derived,
    recovery,
    microtasks,
  )

  const state = {
    ...context,
    ...derived,
    ...recovery,
    ...microtasks,
    ...cycleActions,
  }

  return {
    navigate: state.navigate,
    location: state.location,
    accessControl: state.accessControl,
    subscription: state.subscription,
    getModuleAccess: state.getModuleAccess,
    dashboardUser: state.dashboardUser,
    userId: state.userId,
    trial: state.trial,
    todayEntry: state.todayEntry,
    refetchTodayEntry: state.refetchTodayEntry,
    dailyHistory: state.dailyHistory,
    refetchDailyHistory: state.refetchDailyHistory,
    currentDateKey: state.currentDateKey,
    yesterdayDateKey: state.yesterdayDateKey,
    rawRecoveryTarget: state.rawRecoveryTarget,
    journeyDay: state.journeyDay,
    journeySteps: state.journeySteps,
    microTasks: state.microTasks,
    isFetchingMicroTasks: state.isFetchingMicroTasks,
    refetchMicroTasks: state.refetchMicroTasks,
    createManualTask: state.createManualTask,
    replaceManualTasks: state.replaceManualTasks,
    completeTask: state.completeTask,
    deleteTask: state.deleteTask,
    skipTask: state.skipTask,
    updateProgress: state.updateProgress,
    updateStep: state.updateStep,
    submitDailyCycle: state.submitDailyCycle,
    isGeneratingMicroTasks: state.isGeneratingMicroTasks,
    skipPreviousDay: state.skipPreviousDay,
    isSkippingPreviousDay: state.isSkippingPreviousDay,
    userRole: state.userRole,
    role: state.role,
    isSuperAdmin: state.isSuperAdmin,
    isExpert: state.isExpert,
    name: state.name,
    activeTab: state.activeTab,
    setActiveTab: state.setActiveTab,
    showWheelFrame: state.showWheelFrame,
    setShowWheelFrame: state.setShowWheelFrame,
    showMorningSession: state.showMorningSession,
    setShowMorningSession: state.setShowMorningSession,
    showEveningSession: state.showEveningSession,
    setShowEveningSession: state.setShowEveningSession,
    cycleRecoveryDateKey: state.cycleRecoveryDateKey,
    setCycleRecoveryDateKey: state.setCycleRecoveryDateKey,
    showLevelUpCallout: state.showLevelUpCallout,
    setShowLevelUpCallout: state.setShowLevelUpCallout,
    isExpiredTrialModalOpen: state.isExpiredTrialModalOpen,
    setIsExpiredTrialModalOpen: state.setIsExpiredTrialModalOpen,
    manualTaskText: state.manualTaskText,
    setManualTaskText: state.setManualTaskText,
    manualMicroTask: state.manualMicroTask,
    setManualMicroTask: state.setManualMicroTask,
    isRegeneratingMicroTasks: state.isRegeneratingMicroTasks,
    setIsRegeneratingMicroTasks: state.setIsRegeneratingMicroTasks,
    hasRegeneratedMicroTasks: state.hasRegeneratedMicroTasks,
    setHasRegeneratedMicroTasks: state.setHasRegeneratedMicroTasks,
    microtaskPromptIntent: state.microtaskPromptIntent,
    setMicrotaskPromptIntent: state.setMicrotaskPromptIntent,
    microtaskPromptStage: state.microtaskPromptStage,
    setMicrotaskPromptStage: state.setMicrotaskPromptStage,
    openDayNoticeKey: state.openDayNoticeKey,
    setOpenDayNoticeKey: state.setOpenDayNoticeKey,
    recoveryPromptDateKey: state.recoveryPromptDateKey,
    setRecoveryPromptDateKey: state.setRecoveryPromptDateKey,
    recoveryBlockedIntent: state.recoveryBlockedIntent,
    setRecoveryBlockedIntent: state.setRecoveryBlockedIntent,
    resumeIntentAfterRecovery: state.resumeIntentAfterRecovery,
    setResumeIntentAfterRecovery: state.setResumeIntentAfterRecovery,
    optimisticTaskState: state.optimisticTaskState,
    setOptimisticTaskState: state.setOptimisticTaskState,
    mentorLifecycleState: state.mentorLifecycleState,
    isPausedTrial: state.isPausedTrial,
    currentDay: state.currentDay,
    totalDays: state.totalDays,
    trialDaysLeft: state.trialDaysLeft,
    todayDateKey: state.todayDateKey,
    activeMicrotaskDateKey: state.activeMicrotaskDateKey,
    activeMicrotaskDateLabel: state.activeMicrotaskDateLabel,
    isRecoveryMicrotaskDate: state.isRecoveryMicrotaskDate,
    microtaskContextEntry: state.microtaskContextEntry,
    microtaskContextProgress: state.microtaskContextProgress,
    microtaskContextEntryIds: state.microtaskContextEntryIds,
    morningAnswers: state.morningAnswers,
    morningMeta: state.morningMeta,
    visibleMicroTasks: state.visibleMicroTasks,
    todayMicroTasks: state.todayMicroTasks,
    activeTodayMicroTasks: state.activeTodayMicroTasks,
    completedTodayMicroTasks: state.completedTodayMicroTasks,
    visibleMicroTaskProgress: state.visibleMicroTaskProgress,
    hasActiveMicroTasks: state.hasActiveMicroTasks,
    hasTasksToday: state.hasTasksToday,
    hasRegenEligibleTasks: state.hasRegenEligibleTasks,
    hasMorningAnswers: state.hasMorningAnswers,
    hasServerRegeneratedMicroTasks: state.hasServerRegeneratedMicroTasks,
    canContinueToEvening: state.canContinueToEvening,
    canRegenerateTasks: state.canRegenerateTasks,
    taskDaySteps: state.taskDaySteps,
    completedTaskDaySteps: state.completedTaskDaySteps,
    taskProgressPercent: state.taskProgressPercent,
    taskRingRadius: state.taskRingRadius,
    taskRingCircumference: state.taskRingCircumference,
    taskRingOffset: state.taskRingOffset,
    taskXpToday: state.taskXpToday,
    allTasksResolved: state.allTasksResolved,
    dailyProgressByDate: state.dailyProgressByDate,
    yesterdayEntry: state.yesterdayEntry,
    yesterdayProgress: state.yesterdayProgress,
    recoveryTarget: state.recoveryTarget,
    hasPendingYesterdayGate: state.hasPendingYesterdayGate,
    activeRecoveryProgress: state.activeRecoveryProgress,
    currentFlow: state.currentFlow,
    openDashboardTab: state.openDashboardTab,
    openFlowStep: state.openFlowStep,
    openMicrotasksTab: state.openMicrotasksTab,
    openReportsTab: state.openReportsTab,
    openTodayAfterRecoveryDecision: state.openTodayAfterRecoveryDecision,
    openRecoveryPrompt: state.openRecoveryPrompt,
    openResolvedFlow: state.openResolvedFlow,
    openRecoveryDay: state.openRecoveryDay,
    handleSkipPreviousDay: state.handleSkipPreviousDay,
    handleCatchupFromTodayGuard: state.handleCatchupFromTodayGuard,
    todayGuardBlockState: state.todayGuardBlockState,
    tryOpenToday: state.tryOpenToday,
    handleTodayGuardCatchup: state.handleTodayGuardCatchup,
    handleTodayGuardSkip: state.handleTodayGuardSkip,
    handleTodayGuardDismiss: state.handleTodayGuardDismiss,
    todayGuardYesterdayProgress: state.todayGuardYesterdayProgress,
    todayGuardStepSummary: state.todayGuardStepSummary,
    openFirstIncompleteRecoveryStep: state.openFirstIncompleteRecoveryStep,
    handleFinishYesterday: state.handleFinishYesterday,
    openEveningSession: state.openEveningSession,
    microtaskPromptActive: state.microtaskPromptActive,
    microtaskPromptTitle: state.microtaskPromptTitle,
    microtaskPromptBody: state.microtaskPromptBody,
    openMicrotaskPrompt: state.openMicrotaskPrompt,
    closeMicrotaskPrompt: state.closeMicrotaskPrompt,
    clearMicrotaskNotice: state.clearMicrotaskNotice,
    announceMicrotaskProgress: state.announceMicrotaskProgress,
    handleGenerateMicroTasks: state.handleGenerateMicroTasks,
    handleRegenerateMicroTasks: state.handleRegenerateMicroTasks,
    handleSaveManualTask: state.handleSaveManualTask,
    openEditMicrotaskList: state.openEditMicrotaskList,
    openManualTaskComposer: state.openManualTaskComposer,
    handleCompleteMicroTask: state.handleCompleteMicroTask,
    handleSkipMicroTask: state.handleSkipMicroTask,
    serializeVisibleMicroTaskList: state.serializeVisibleMicroTaskList,
    saveVisibleManualTask: state.saveVisibleManualTask,
    startMorningFromCycle: state.startMorningFromCycle,
    startEveningFromCycle: state.startEveningFromCycle,
    showTasksFromCycle: state.showTasksFromCycle,
    handleCycleComplete: state.handleCycleComplete,
  }
}

export type DashboardState =
  ReturnType<typeof useDashboardState>
