import type { ResearchConfig } from './types.js'

function getCurrentMonthYear() {
  return {
    month: String(new Date().getMonth() + 1),
    year: String(new Date().getFullYear()),
  }
}

export function buildFallbackResearch(config: ResearchConfig) {
  const { month, year } = getCurrentMonthYear()

  if (config.type === 'hooks') {
    return {
      hooks: [
        {
          id: 'reframe_1',
          type: 'reframe',
          example: 'Ти стараєшся все втримати, але всередині вже давно немає ресурсу.',
          why: 'Знімає провину → будує довіру → показує простий перший крок.',
          watchTimeBoost: 42,
          ctrBoost: 0,
          source: 'Coaching niche synthetic benchmark',
          bestFor: ['BOFU', 'warm_audience'],
          platforms: ['instagram', 'meta_ads'],
          formula: 'PAS',
          month,
          year,
        },
        {
          id: 'story_1',
          type: 'story',
          example: 'Тобі знайоме це відчуття о 23:58?',
          why: 'Конкретна деталь + знайоме відчуття зупиняють скрол і ведуть у зміну стану.',
          watchTimeBoost: 38,
          ctrBoost: 0,
          source: 'Storytelling coaching benchmark',
          bestFor: ['MOFU', 'warm_audience'],
          platforms: ['instagram'],
          formula: 'PAS',
          month,
          year,
        },
        {
          id: 'data_1',
          type: 'data',
          example: 'Коли руху нема, цифри показують де саме ламається шлях.',
          why: 'Specificity + credibility працюють, коли цифри ведуть до зрозумілого кроку.',
          watchTimeBoost: 27,
          ctrBoost: 27,
          source: 'Performance ad benchmark',
          bestFor: ['MOFU', 'cold_audience'],
          platforms: ['instagram', 'meta_ads'],
          formula: 'AIDA',
          month,
          year,
        },
        {
          id: 'gap_1',
          type: 'gap',
          example: 'Більшість здаються. Ось що допомагає не зірватися.',
          why: 'Відкрита петля тримає увагу, коли є знайоме впізнавання і обіцянка простого виходу.',
          watchTimeBoost: 31,
          ctrBoost: 0,
          source: 'Curiosity-gap short video benchmark',
          bestFor: ['TOFU', 'cold_audience'],
          platforms: ['instagram'],
          formula: 'BAB',
          month,
          year,
        },
        {
          id: 'question_1',
          type: 'question',
          example: 'Ти ведеш щоденник чи просто гасиш пожежі?',
          why: 'Питання одразу включає людину в самодіагностику.',
          watchTimeBoost: 24,
          ctrBoost: 12,
          source: 'Direct response coaching prompt bank',
          bestFor: ['TOFU', 'warm_audience'],
          platforms: ['instagram'],
          formula: 'BAB',
          month,
          year,
        },
        {
          id: 'contradiction_1',
          type: 'contradiction',
          example: 'Проблема не в мотивації. Проблема в системі.',
          why: 'Контраст ламає стару рамку і веде в новий кут подачі.',
          watchTimeBoost: 29,
          ctrBoost: 15,
          source: 'Contrarian coaching hooks',
          bestFor: ['BOFU', 'warm_audience'],
          platforms: ['instagram', 'meta_ads'],
          formula: 'PAS',
          month,
          year,
        },
        {
          id: 'before_after_1',
          type: 'before_after',
          example: 'Ще вчора: хаос. Через 7 днів: структура, стрік, результат.',
          why: 'До/після швидко продає відчутну зміну.',
          watchTimeBoost: 26,
          ctrBoost: 18,
          source: 'Transformation reels benchmark',
          bestFor: ['BOFU', 'warm_audience'],
          platforms: ['instagram'],
          formula: 'BAB',
          month,
          year,
        },
        {
          id: 'social_proof_1',
          type: 'social_proof',
          example: '24 учні вже зібрали собі систему без хаосу.',
          why: 'Соціальний доказ зменшує недовіру на вході.',
          watchTimeBoost: 19,
          ctrBoost: 21,
          source: 'Coaching social proof benchmark',
          bestFor: ['MOFU', 'BOFU'],
          platforms: ['instagram', 'meta_ads'],
          formula: '4P',
          month,
          year,
        },
      ],
    }
  }

  if (config.type === 'ads') {
    return {
      campaigns: [
        {
          id: 'campaign_storytelling',
          brand: 'Coaching brand',
          hook: 'Тобі знайоме це відчуття о 23:58?',
          formula: 'PAS',
          hookType: 'story',
          metric: 'CTR +38%',
          metricValue: 38,
          metricType: 'ctr',
          description: 'Конкретний момент і знайоме відчуття зупиняють скрол. Потім — коротке впізнавання, спокій і міст до рішення.',
          audienceTemp: 'warm',
          platform: config.platform,
          format: 'reels',
          month,
          year,
        },
        {
          id: 'campaign_reframe',
          brand: 'Self-dev coaching',
          hook: 'Ти тягнеш усе сама, і саме це виснажує найбільше.',
          formula: 'PAS',
          hookType: 'reframe',
          metric: 'Watch time +42%',
          metricValue: 42,
          metricType: 'watch_time',
          description: 'Спочатку знімаємо самозвинувачення, потім будуємо довіру і показуємо перший зрозумілий крок.',
          audienceTemp: 'warm',
          platform: config.platform,
          format: 'reels',
          month,
          year,
        },
        {
          id: 'campaign_data',
          brand: 'Health-tech coaching',
          hook: 'Коли руху нема, цифри показують де саме ламається шлях.',
          formula: 'AIDA',
          hookType: 'data',
          metric: 'CTR +27%',
          metricValue: 27,
          metricType: 'ctr',
          description: 'Специфічна цифра зупиняє більше, ніж округлена. Дані працюють, коли вони ведуть до зрозумілого кроку.',
          audienceTemp: 'cold',
          platform: config.platform,
          format: 'meta_ad',
          month,
          year,
        },
        {
          id: 'campaign_gap',
          brand: 'Coaching niche',
          hook: 'Більшість здаються. Ось що допомагає не зірватися.',
          formula: 'BAB',
          hookType: 'gap',
          metric: 'Watch time +31%',
          metricValue: 31,
          metricType: 'watch_time',
          description: 'Open loop тримає увагу, коли всередині є знайоме впізнавання і обіцянка простого виходу.',
          audienceTemp: 'cold',
          platform: config.platform,
          format: 'reels',
          month,
          year,
        },
        {
          id: 'campaign_fab',
          brand: 'Productivity mentor',
          hook: 'AI нагадує тобі не просто задачу, а простий наступний крок.',
          formula: 'FAB',
          hookType: 'feature',
          metric: 'Leads +22%',
          metricValue: 22,
          metricType: 'leads',
          description: 'Раціональна подача через користь продукту добре працює на теплій аудиторії.',
          audienceTemp: 'warm',
          platform: config.platform,
          format: 'feed',
          month,
          year,
        },
        {
          id: 'campaign_stack',
          brand: 'Premium mentoring',
          hook: 'Reels + DM + Bot + Trial → один зрозумілий маршрут до оплати.',
          formula: 'STACK',
          hookType: 'contradiction',
          metric: 'ROAS 3.8x',
          metricValue: 3.8,
          metricType: 'roas',
          description: 'Стекова логіка добре заходить, коли продаємо не один пост, а систему продажів.',
          audienceTemp: 'hot',
          platform: config.platform,
          format: 'meta_ad',
          month,
          year,
        },
      ],
    }
  }

  if (config.type === 'formulas') {
    return {
      formulas: [
        {
          id: 'pas',
          name: 'PAS',
          fullName: 'Problem · Agitate · Solution',
          conversionBoost: 42,
          bestFor: 'BOFU, warm audience, coaching',
          worstFor: 'very cold awareness traffic',
          steps: ['P: проблема', 'A: посилення', 'S: рішення'],
          example: 'Ти стараєшся, але результат усе ще не приходить. ABsystem збирає систему за тебе.',
          rank: 1,
          trending: true,
          month,
          year,
        },
        {
          id: 'aida',
          name: 'AIDA',
          fullName: 'Attention · Interest · Desire · Action',
          conversionBoost: 34,
          bestFor: 'cold ads, awareness',
          worstFor: 'короткий BOFU добір',
          steps: ['A: увага', 'I: інтерес', 'D: бажання', 'A: дія'],
          example: 'Стоп. Це про тебе, якщо день знову розсипається. Спробуй 7 днів і відчуй різницю сама.',
          rank: 2,
          trending: true,
          month,
          year,
        },
        {
          id: 'bab',
          name: 'BAB',
          fullName: 'Before · After · Bridge',
          conversionBoost: 29,
          bestFor: 'stories, reels, transformation',
          worstFor: 'сухі технічні офери',
          steps: ['Before', 'After', 'Bridge'],
          example: 'Ще вчора: хаос і ручна тяганина. Через 7 днів: ритм, ясність і відчуття контролю.',
          rank: 3,
          trending: true,
          month,
          year,
        },
        {
          id: 'fab',
          name: 'FAB',
          fullName: 'Feature · Advantage · Benefit',
          conversionBoost: 24,
          bestFor: 'раціональні сегменти',
          worstFor: 'емоційний прогрів',
          steps: ['Feature', 'Advantage', 'Benefit'],
          example: 'AI аналізує твій стан щодня. Результат — не губиш ритм.',
          rank: 4,
          trending: false,
          month,
          year,
        },
        {
          id: '4p',
          name: '4P',
          fullName: 'Promise · Picture · Proof · Push',
          conversionBoost: 22,
          bestFor: 'соціальний доказ і прогрів',
          worstFor: 'дуже короткі hooks',
          steps: ['Promise', 'Picture', 'Proof', 'Push'],
          example: 'Я покажу, як вийти із застою без зайвого шуму. Люди вже проходять цей маршрут і не починають з нуля.',
          rank: 5,
          trending: false,
          month,
          year,
        },
        {
          id: 'stack',
          name: 'STACK',
          fullName: 'PAS + FAB + CTA',
          conversionBoost: 34,
          bestFor: 'комплексні пакети і funnel-sale',
          worstFor: 'простий single-offer lead magnet',
          steps: ['Problem', 'Offer stack', 'Proof', 'CTA'],
          example: 'Спочатку зачіпаємо біль, потім швидко показуємо рішення і закриваємо простим CTA.',
          rank: 6,
          trending: true,
          month,
          year,
        },
      ],
    }
  }

  return {
    trends: [
      {
        id: 'trend_direct',
        format: 'Direct-to-camera',
        hookText: 'Ти стараєшся все тримати під контролем, але сил уже не вистачає.',
        watchTimeBoost: 38,
        description: 'Короткий прямий початок без заставок і складного монтажу.',
        duration: '15-30 sec',
        structure: ['0-3 sec: hook', '3-12 sec: body', '12-15 sec: CTA'],
        example: 'Reels про хаос, структуру і 7-денний trial.',
        trending: true,
        month,
        year,
      },
      {
        id: 'trend_story',
        format: 'Micro-story',
        hookText: 'Тобі знайоме це відчуття о 23:58?',
        watchTimeBoost: 36,
        description: 'Особиста сцена добре тримає увагу в coaching ніші.',
        duration: '20-35 sec',
        structure: ['story hook', 'insight', 'offer'],
        example: 'Кейс учениці, яка зібрала систему за 7 днів.',
        trending: true,
        month,
        year,
      },
      {
        id: 'trend_data',
        format: 'Data-first reels',
        hookText: 'Коли руху нема, цифри показують де саме ламається шлях.',
        watchTimeBoost: 27,
        description: 'Цифра + питання швидко зупиняє скрол.',
        duration: '15-25 sec',
        structure: ['data', 'meaning', 'CTA'],
        example: 'Метрика звички й дисципліни через ABsystem.',
        trending: true,
        month,
        year,
      },
      {
        id: 'trend_curiosity',
        format: 'Curiosity loop',
        hookText: 'Більшість здаються. Ось що допомагає не зірватися.',
        watchTimeBoost: 31,
        description: 'Open loop підходить для прогріву й переходу в DM.',
        duration: '12-20 sec',
        structure: ['gap', 'bridge', 'CTA'],
        example: 'Чому одні тримають стрік, а інші ні.',
        trending: true,
        month,
        year,
      },
      {
        id: 'trend_checklist',
        format: 'Checklist visual',
        hookText: '3 сигнали, що в тебе не проблема з контентом, а з системою',
        watchTimeBoost: 24,
        description: 'Списки дають швидку ясність і добре працюють у B2C coaching.',
        duration: '20-30 sec',
        structure: ['headline', '3 points', 'CTA'],
        example: 'Checklist для експерта перед запуском funnel.',
        trending: false,
        month,
        year,
      },
      {
        id: 'trend_overlay',
        format: 'Subtitle-led reel',
        hookText: 'Коли ти постиш, але заявок немає',
        watchTimeBoost: 22,
        description: 'Сильні субтитри витягують слабший відеоряд.',
        duration: '15-30 sec',
        structure: ['title', 'subtitles', 'CTA'],
        example: 'Reels з мінімальним монтажем і сильним меседжем.',
        trending: false,
        month,
        year,
      },
    ],
  }
}

export function shouldUseFallbackResearch(error: unknown) {
  if (!(error instanceof Error)) return true
  return /429|quota|rate limit|timeout|network|fetch/i.test(error.message)
}
