// frontend/src/features/ai-generator/utils/templates.ts

import { FunnelBlueprint } from "@/features/ai-generator/types/generator.types";

export const DEMO_TEMPLATES: FunnelBlueprint[] = [
  {
    id: 'template1',
    name: 'AI-Аудит: Де ти втрачаєш гроші',
    type: 'fast_cash',
    targetAudience: 'Експерти, фрілансери, малі бізнеси без стабільних продажів',
    painPoint: 'Продукт не продається, незрозуміло чому',
    quickWin: 'PDF-звіт з 3 головними помилками за 5 хвилин',
    coreOffer: {
      name: 'Персональний AI-розбір + план дій',
      price: 99,
      format: 'AI-супровід + документація',
    },
    upsell: {
      name: 'AI-воронка під твій продукт',
      price: 299,
    },
    financialModel: {
      targetRevenue: 10000,
      averageCheck: 99,
      requiredSales: 101,
      conversion_rate: 18,
    },
    automation: [
      'AI-діагностика автоматична',
      'Генерація PDF-звіту',
      'Email-секвенція',
      'Telegram-нагадування',
    ],
    steps: {
      hook: 'Хочеш знати, чому твій продукт не продається? AI знайде причину за 2 хвилини',
      diagnostic: '5 питань про продукт, трафік, офер → AI виявляє 3 фейли',
      quickWin: 'Безкоштовний PDF з розбором + voice-коментар AI',
      coreOffer: 'Персональний AI-план на 14 днів: що змінити, як протестувати, чого чекати',
      upsell: 'Хочеш AI зробить це за тебе? Готова воронка + інтеграції за 299 грн',
    },
    products: [
      {
        id: 'audit-basic',
        name: 'AI-Аудит (основний)',
        type: 'one-time',
        price: 99,
        format: 'web',
        integration: 'other',
        includesMentorship: false,
        goal: 'lead',
        purpose: 'збір потенційних клієнтів',
      },
      {
        id: 'audit-upsell',
        name: 'Повна AI-воронка під ключ',
        type: 'one-time',
        price: 299,
        format: 'mini-app',
        integration: 'telegram',
        includesMentorship: true,
        goal: 'sale',
        purpose: 'продаж повного пакету',
      },
    ],
  },

  {
    id: 'diagnostic',
    name: 'AI-Діагностика твого доходу',
    type: 'diagnostic',
    targetAudience: 'Експерти, коучі, онлайн-школи з продуктом але без стабільного доходу',
    painPoint: 'Є продукт, є аудиторія, але гроші нестабільні',
    quickWin: 'Персональний AI-звіт: продукт VS воронка VS трафік',
    coreOffer: {
      name: 'AI-Стратегія росту',
      price: 399,
      format: 'Стратегічна сесія + roadmap',
    },
    upsell: {
      name: 'Повна AI-воронка під ключ',
      price: 999,
    },
    financialModel: {
      targetRevenue: 50000,
      averageCheck: 399,
      requiredSales: 125,
      conversion_rate: 15,
    },
    automation: [
      'AI-аналіз бізнес-моделі',
      'Автоматичні рекомендації',
      'Email + Telegram-секвенція',
      'Трекінг виконання',
    ],
    steps: {
      hook: 'Твій дохід — проблема продукту чи воронки? AI дасть відповідь за 3 хвилини',
      diagnostic: 'AI аналізує: якість продукту, позиціонування, джерела трафіку, конверсію',
      quickWin: 'Детальний звіт з цифрами: де втрачаєш, скільки і як виправити',
      coreOffer: 'AI-Стратегія: покроковий план виходу на стабільний дохід за 30-60 днів',
      upsell: 'AI збудує всю воронку: лендинг, бот, email, аналітику — готове рішення',
    },
    products: [
      {
        id: 'diagnostic-strategy',
        name: 'AI-Стратегія росту',
        type: 'one-time',
        price: 399,
        format: 'web',
        integration: 'other',
        includesMentorship: false,
        goal: 'sale',
        purpose: 'продаж повного пакету',
      },
      {
        id: 'diagnostic-full-funnel',
        name: 'Повна воронка під ключ',
        type: 'one-time',
        price: 999,
        format: 'mini-app',
        integration: 'telegram',
        includesMentorship: true,
        goal: 'sale',
        purpose: 'продаж повного пакету',
      },
    ],
  },

  {
    id: 'ai-mentorship',
    name: 'AI: Досвід → Продажі',
    type: 'evergreen',
    targetAudience: 'Контент-кріейтори, блогери, експерти з аудиторією',
    painPoint: 'Багато контенту, лайків, але продажів немає',
    quickWin: 'AI-чеклист: чому контент не конвертує',
    coreOffer: {
      name: 'AI-Контент + мікроворонка',
      price: 79,
      format: 'Контент-план + автоворонка',
    },
    upsell: {
      name: 'AI-Контент машина (місяць)',
      price: 199,
    },
    financialModel: {
      targetRevenue: 30000,
      averageCheck: 79,
      requiredSales: 380,
      conversion_rate: 12,
    },
    automation: [
      'AI-генерація контенту',
      'Автопублікація',
      'Мікроворонка на кожен пост',
      'Аналітика engagement',
    ],
    steps: {
      hook: 'Чому твій контент набирає лайки, але не продає? AI покаже за 1 хвилину',
      diagnostic: 'AI перевіряє: теми, CTA, структуру, зв\'язок з офером',
      quickWin: 'Чеклист з 7 пунктів + 3 готові продаючі теми під твій продукт',
      coreOffer: 'AI створює 14 днів контенту + мікроворонку під кожен пост',
      upsell: 'Підписка: AI генерує контент щодня + автоматично веде до продажу',
    },
    products: [
      {
        id: 'content-plan',
        name: 'AI-Контент план на 14 днів',
        type: 'one-time',
        price: 79,
        format: 'web',
        integration: 'other',
        includesMentorship: false,
        goal: 'lead',
        purpose: 'збір потенційних клієнтів',
      },
      {
        id: 'content-subscription',
        name: 'AI-Контент машина (підписка)',
        type: 'subscription',
        price: 199,
        format: 'mini-app',
        integration: 'telegram',
        includesMentorship: false,
        goal: 'sale',
        purpose: 'щоденний продаж контенту',
      },
    ],
  },
];
