import { cn } from '@/lib/utils'

export const dashboardDesignSystem = {
  colors: {
    primary: '#4f8ef7',
    primarySoft: '#7eb3ff',
    primaryMuted: '#6ea4ff',
    success: '#4ade80',
    warning: '#fbbf24',
    danger: '#ff7d82',
    background: '#080e1a',
    surface: 'rgba(12,18,33,0.78)',
    panel: 'rgba(23,29,43,0.9)',
    panelStrong: 'rgba(26,31,46,0.92)',
    border: 'rgba(255,255,255,0.1)',
    textPrimary: '#ffffff',
    textSecondary: 'rgba(255,255,255,0.78)',
    textMuted: 'rgba(255,255,255,0.45)',
    pathIdle: 'rgba(255,255,255,0.10)',
    pathDone: 'rgba(74,222,128,0.85)',
    pathActive: 'rgba(99,160,255,0.65)',
    pathActiveMuted: 'rgba(99,160,255,0.20)',
  },
  typography: {
    headingLg: 'text-[clamp(1.65rem,2vw,2rem)] font-semibold tracking-tight text-white',
    headingMd: 'text-[clamp(1.2rem,1.6vw,1.5rem)] font-medium text-white/78',
    headingSm: 'text-[clamp(1.05rem,1.4vw,1.2rem)] font-semibold text-white',
    body: 'text-[clamp(1.15rem,1.5vw,1.35rem)] font-medium text-white',
    bodyMuted: 'text-[clamp(1.15rem,1.6vw,1.5rem)] font-medium leading-relaxed text-white/78',
    subtitle: 'text-[clamp(1rem,1.2vw,1.15rem)] font-medium',
    label: 'text-[11px] font-semibold uppercase tracking-[0.28em]',
    overline: 'text-[10px] font-medium uppercase tracking-[0.32em] text-white/28',
    helper: 'text-sm text-white/38',
  },
  spacing: {
    stackXs: 'space-y-3',
    stackSm: 'space-y-4',
    stackMd: 'space-y-6',
    stackLg: 'space-y-8',
    stackXl: 'gap-10',
    inlineSm: 'gap-2',
    inlineMd: 'gap-4',
    inlineLg: 'gap-8',
  },
  radius: {
    lg: 'rounded-2xl',
    surface: 'rounded-[28px]',
    card: 'rounded-[24px]',
    cardSoft: 'rounded-[22px]',
    button: 'rounded-[24px]',
    pill: 'rounded-[20px]',
    circle: 'rounded-full',
  },
  surfaces: {
    page: 'min-h-screen bg-[linear-gradient(180deg,#070d1b_0%,#090f1d_100%)]',
    container: 'mx-auto flex w-full max-w-[1140px] flex-col gap-10',
    segmented: 'rounded-[28px] border border-white/10 bg-[rgba(12,18,33,0.78)] p-1.5',
    card: 'rounded-[24px] border border-white/10 bg-[rgba(23,29,43,0.9)]',
    panel: 'rounded-[22px] border border-white/10 bg-[rgba(26,31,46,0.92)]',
    alert: 'rounded-[26px] border border-[rgba(201,79,86,0.35)] bg-[rgba(28,20,30,0.88)]',
  },
  fields: {
    input:
      'h-[72px] w-full rounded-[22px] border border-white/10 bg-[rgba(26,31,46,0.92)] px-6 text-[clamp(1.2rem,1.6vw,1.4rem)] font-medium text-white outline-none transition-all duration-200 placeholder:text-white/18 focus:border-[rgba(99,160,255,.35)] focus:shadow-[0_0_0_3px_rgba(59,130,246,0.12)]',
    textarea:
      'min-h-[110px] w-full rounded-[22px] border border-white/10 bg-[rgba(23,29,43,0.9)] px-6 py-5 text-[clamp(1.15rem,1.5vw,1.35rem)] font-medium text-white outline-none transition-all duration-200 placeholder:text-white/18 focus:border-[rgba(99,160,255,.35)] focus:shadow-[0_0_0_3px_rgba(59,130,246,0.12)]',
  },
  buttons: {
    primary:
      'hero-cta-primary flex h-[82px] w-full items-center justify-center rounded-[24px] text-[clamp(1.3rem,1.8vw,1.7rem)] font-semibold',
    secondary:
      'inline-flex h-[68px] min-w-[170px] items-center justify-center gap-3 rounded-[20px] border border-white/10 bg-[rgba(24,28,43,0.95)] px-8 text-[clamp(1.15rem,1.4vw,1.45rem)] font-semibold text-white/75 transition-colors hover:bg-white/[0.05] hover:text-white',
    ghost:
      'inline-flex h-[64px] min-w-[200px] items-center justify-center gap-3 rounded-[20px] bg-[rgba(56,114,255,0.16)] px-8 text-[clamp(1.15rem,1.4vw,1.45rem)] font-semibold text-white transition-colors hover:bg-[rgba(56,114,255,0.22)]',
    gold:
      'inline-flex h-12 w-full items-center justify-center gap-2 rounded-2xl bg-[linear-gradient(135deg,#F5C451,#D4A017)] text-sm font-semibold text-[#1b1b1b] transition duration-200 hover:brightness-110',
  },
  tabs: {
    track: 'grid grid-cols-3 gap-1.5',
    item: 'rounded-[22px] px-4 py-4 text-center text-[clamp(1.05rem,1.4vw,1.2rem)] font-semibold transition-all duration-200',
    itemActive: 'bg-[rgba(31,44,74,0.95)] text-white shadow-[inset_0_1px_0_rgba(255,255,255,0.05)]',
    itemInactive: 'text-white/45 hover:text-white/70',
  },
  step: {
    iconBase: 'relative z-[1] flex h-12 w-12 items-center justify-center rounded-full border text-sm font-semibold transition-colors',
    iconDone: 'border-[rgba(74,222,128,.45)] bg-[rgba(74,222,128,.10)] text-[#4ade80]',
    iconActive: 'border-[rgba(99,160,255,.45)] bg-[rgba(99,160,255,.10)] text-[#7eb3ff]',
    iconLocked: 'border-white/10 bg-white/[0.03] text-white/28',
    labelDone: 'text-[#35c16f]',
    labelActive: 'text-white',
    labelLocked: 'text-white/35',
  },
  goals: {
    stepBadge: 'flex h-11 w-11 items-center justify-center rounded-full bg-[rgba(56,114,255,0.18)] text-xl font-semibold text-[#6ea4ff]',
    inputIndex: 'flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-[rgba(52,93,180,0.28)] text-xl font-semibold text-[#78a8ff]',
    dangerLabel: 'text-[#ff7d82]',
    todayProgress: 'h-[6px] w-full rounded-full bg-[linear-gradient(90deg,rgba(255,115,115,0.0),rgba(255,115,115,0.32),rgba(255,115,115,0.0))]',
  },
  journey: {
    section: 'relative',
    canvas: 'pointer-events-none absolute inset-0 z-0 h-full w-full',
    list: 'relative z-10 flex flex-col gap-0',
    row: 'mb-0 flex items-start',
    rowLeft: 'justify-start',
    rowRight: 'justify-end',
    spacer: 'h-7',
    nodeBase:
      'relative z-20 mt-3.5 flex h-7 w-7 shrink-0 items-center justify-center rounded-full border-2 text-xs font-medium',
    nodeOffsetLeft: 'ml-2',
    nodeOffsetRight: 'mr-2',
    nodeDone: 'border-[#4ade80] bg-[#080e1a] text-[#4ade80] shadow-[0_0_0_5px_rgba(74,222,128,0.10)]',
    nodeActive: 'border-[#7eb3ff] bg-[#080e1a] text-[#7eb3ff] shadow-[0_0_0_6px_rgba(99,160,255,0.12)]',
    nodeLocked: 'border-white/15 bg-[#080e1a] text-white/25',
    cardWrap: 'relative w-[78%]',
    cardBase: 'overflow-hidden bg-[rgba(23,29,43,0.9)] transition-all duration-200',
    cardExpanded: 'rounded-t-[14px] border border-b-0',
    cardCollapsed: 'rounded-[14px] border',
    cardDone: 'border-[rgba(74,222,128,0.22)]',
    cardActive: 'border-[rgba(99,160,255,0.30)] bg-[#0e1b30]',
    cardLocked: 'cursor-default border-white/10 opacity-55',
    cardInteractive: 'cursor-pointer hover:border-white/15',
    cardInner: 'flex items-start gap-2.5 px-3.5 py-[13px]',
    stepIndex: 'mb-0.5 text-[10px] tracking-[.06em] text-white/22',
    stepTitle: 'text-[13px] font-medium text-white',
    stepSubtitle: 'mt-0.5 text-[11px] text-white/35',
    progressRow: 'mt-1.5 flex items-center gap-2',
    progressTrack: 'h-0.5 flex-1 rounded-full bg-white/6',
    progressBar: 'h-0.5 rounded-full transition-all duration-500',
    progressDone: 'w-full bg-[#4ade80]',
    progressActive: 'w-[15%] bg-[#7eb3ff]',
    progressLocked: 'w-0 bg-transparent',
    rewardBase: 'whitespace-nowrap text-[10px]',
    rewardDone: 'text-[rgba(74,222,128,0.55)]',
    rewardActive: 'text-[rgba(99,160,255,0.55)]',
    rewardLocked: 'text-[rgba(255,255,255,0.15)]',
    chevron: 'text-[10px] text-white/22 transition-transform duration-300',
    panelBase:
      'overflow-hidden rounded-b-[14px] border border-t-0 bg-[#0d1929] transition-[max-height,opacity] duration-300 ease-in-out',
    panelOpen: 'max-h-[640px] opacity-100',
    panelClosed: 'max-h-0 opacity-0',
    panelActive: 'border-[rgba(99,160,255,0.20)]',
    panelLocked: 'border-[rgba(251,191,36,0.15)]',
    panelInner: 'px-[13px] py-[14px]',
    overline: 'mb-2 text-[10px] uppercase tracking-[.1em] text-white/25',
    scoreName: 'flex-1 truncate text-[11px] text-white/50',
    scoreValue: 'min-w-[13px] text-right text-[11px] font-medium text-white',
    scoreLabel: 'min-w-[82px] text-[11px] text-white/60',
    scoreNumber: 'min-w-[16px] text-right text-[11px] font-medium text-white',
    buttonRow: 'mt-4 flex flex-wrap gap-3',
    buttonSecondary:
      'flex-1 rounded-lg border border-white/10 bg-white/5 py-2.5 text-xs text-white transition-colors hover:bg-white/10',
    buttonPrimary: 'hero-cta-primary flex-1 rounded-lg py-2.5 text-xs',
    detailsWrap: 'mt-3 overflow-hidden rounded-[10px] border border-white/10 bg-[rgba(23,29,43,0.9)]',
    detailsScroll: 'max-h-[480px] overflow-y-auto p-3 pr-2',
    statsGrid: 'grid gap-2 sm:grid-cols-4',
    detailCard: 'rounded-[10px] border border-white/10 bg-[#0d1929] p-3',
    detailCardLg: 'rounded-[10px] border border-white/10 bg-[#0d1929] p-5',
    detailHeader: 'flex flex-wrap items-start justify-between gap-3 rounded-[10px] border border-white/10 bg-[#0d1929] p-3',
    detailKicker: 'text-[10px] uppercase tracking-[.14em] text-white/25',
    detailTitle: 'mt-1 text-[13px] font-medium text-white',
    detailDate: 'text-[12px] font-medium text-white',
    detailMeta: 'mt-0.5 text-[11px] text-white/40',
    detailStatLabel: 'text-[10px] uppercase tracking-[.12em] text-white/25',
    detailStatValue: 'mt-2 text-[20px] font-semibold text-white',
    detailChartRow: 'mb-3 flex flex-wrap items-start gap-6 lg:flex-nowrap',
    detailLegend: 'min-w-[220px] flex-1 space-y-2 pt-1 sm:pl-4',
    detailRegularText: 'mt-2 text-[12px] leading-snug text-white/70',
    detailSecondaryText: 'mt-2 text-[11px] text-white/45',
    alertCard: 'rounded-[10px] border border-[rgba(251,191,36,0.18)] bg-[rgba(251,191,36,0.06)] p-3',
    alertText: 'text-[12px] font-medium text-[#fbbf24]',
    actionGrid: 'grid gap-2 sm:grid-cols-2 xl:grid-cols-4',
    actionButton: 'rounded-lg border border-white/10 bg-white/5 py-2.5 text-xs text-white transition-colors hover:bg-white/10',
    emptyIcon:
      'mx-auto flex h-11 w-11 items-center justify-center rounded-full border border-white/10 bg-white/5 text-lg text-white/55',
    emptyTitle: 'mt-3 text-[14px] font-medium text-white',
    emptyText: 'mx-auto mt-2 max-w-[360px] text-[12px] leading-snug text-white/60',
    goalsRow: 'mb-1.5 flex items-start gap-2 rounded-lg border border-white/10 bg-[rgba(23,29,43,0.9)] px-2.5 py-2',
    goalsIndexBase: 'mt-px flex h-[18px] w-[18px] shrink-0 items-center justify-center rounded-full text-[10px]',
    goalsIndexActive: 'bg-[rgba(99,160,255,.15)] text-[#7eb3ff]',
    goalsIndexIdle: 'bg-[#1a2a40] text-[rgba(255,255,255,.38)]',
    goalsText: 'flex-1 text-[12px] leading-snug text-white/65',
    goalsTagBase: 'whitespace-nowrap rounded-[5px] px-1.5 py-0.5 text-[10px]',
    goalsTagDay: 'bg-[rgba(99,160,255,.13)] text-[#93c5fd]',
    goalsTagWeek: 'bg-[rgba(139,92,246,.13)] text-[#c4b5fd]',
    goalsTagMonth: 'bg-[rgba(20,184,166,.13)] text-[#5eead4]',
    iconButton:
      'ml-1 flex h-5 w-5 shrink-0 items-center justify-center rounded-[5px] border border-white/10 bg-white/5 text-[10px] text-white/40 transition-colors hover:bg-white/10',
    saveButton: 'hero-cta-primary mt-2 w-full rounded-[9px] py-[11px] text-[13px]',
    lockedCard:
      'flex items-center gap-2.5 rounded-[9px] border border-[rgba(251,191,36,0.18)] bg-[rgba(251,191,36,0.06)] px-[13px] py-[11px]',
    lockedTitle: 'mb-0.5 text-[12px] font-medium text-[#fbbf24]',
    lockedText: 'text-[11px] leading-snug text-white/35',
    lockedButton:
      'shrink-0 whitespace-nowrap rounded-[7px] border border-[rgba(251,191,36,0.28)] bg-[rgba(251,191,36,0.12)] px-[11px] py-[7px] text-[11px] font-medium text-[#fbbf24] transition-colors hover:bg-[rgba(251,191,36,.22)]',
  },
  vision: {
    shell: 'space-y-6',
    section:
      'rounded-3xl border border-white/10 bg-[rgba(10,16,31,0.82)] p-6 text-white shadow-[0_20px_60px_rgba(0,0,0,0.25)]',
    sectionSoft: 'rounded-3xl border border-white/10 bg-white/[0.03] p-4',
    trialBanner:
      'rounded-3xl border border-[rgba(92,136,255,0.18)] bg-[linear-gradient(180deg,rgba(42,77,155,0.22),rgba(11,19,37,0.92))] p-5 text-white shadow-[0_18px_48px_rgba(8,15,32,0.28)]',
    overline: 'text-xs uppercase tracking-[0.28em] text-[var(--accent-soft)]',
    overlineSoft: 'text-xs uppercase tracking-[0.24em] text-[var(--accent-soft)]',
    microLabel: 'text-[11px] font-semibold uppercase tracking-[0.24em] text-[rgb(var(--accent-soft-rgb))]',
    titleLg: 'mt-3 text-2xl font-semibold text-white',
    titleMd: 'mt-2 text-xl font-semibold text-white',
    titleSm: 'mt-2 text-base font-semibold text-white',
    body: 'mt-2 text-sm text-white/72',
    bodyMuted: 'text-sm leading-6 text-white/70',
    helper: 'mt-2 text-sm text-white/55',
    meta: 'text-sm text-white/75',
    pill: 'rounded-full border border-white/10 bg-white/[0.04] px-3 py-1 text-sm text-white/70',
    pillLg: 'rounded-2xl border border-white/10 bg-white/[0.04] px-4 py-3 text-sm text-white/75',
    ctaSoft:
      'rounded-2xl border border-[rgba(92,136,255,0.24)] bg-[rgba(92,136,255,0.14)] px-4 py-3 text-sm font-semibold text-[rgb(var(--accent-soft-rgb))] transition-colors duration-150 hover:bg-[rgba(92,136,255,0.2)]',
    currentCard:
      'border-[rgba(92,136,255,0.35)] bg-[rgba(92,136,255,0.12)] shadow-[0_0_24px_rgba(92,136,255,0.16)]',
    defaultCard: 'border-white/10 bg-white/[0.03]',
    doneCard: 'border-emerald-500/20 bg-emerald-500/[0.08]',
    chipActive: 'rounded-full border border-[var(--accent-soft)] bg-[rgba(92,136,255,0.16)] px-4 py-2 text-sm text-white',
    chipMuted: 'rounded-full border border-white/10 px-2 py-1 text-xs text-white/55',
    aiCard: 'relative overflow-hidden rounded-2xl border border-white/10 bg-white/[0.03] p-4',
    aiOverlayTop: 'pointer-events-none absolute inset-0 bg-[linear-gradient(180deg,rgba(255,255,255,0.06),rgba(255,255,255,0.02))]',
    aiOverlayBase: 'pointer-events-none absolute inset-0 bg-[rgba(10,16,31,0.42)]',
    tabButtonBase: 'rounded-full border px-4 py-2 text-sm transition-colors',
    tabButtonActive: 'border-[var(--accent-soft)] bg-[rgba(92,136,255,0.16)] text-white',
    tabButtonIdle: 'border-white/10 bg-white/[0.03] text-white/65 hover:text-white',
    progressTrack: 'mt-2 h-2 rounded-full bg-white/10',
    progressFill: 'h-full rounded-full bg-[rgb(var(--accent-rgb))] transition-all duration-300',
    widgetButton:
      'mt-4 w-full rounded-2xl border border-[var(--border-primary)] bg-[rgba(10,16,31,0.82)] p-3 text-left transition-colors hover:border-[rgba(var(--accent-rgb),0.26)] hover:bg-[rgba(12,19,36,0.94)]',
    widgetLabel: 'text-[10px] font-semibold uppercase tracking-[0.18em] text-[rgb(var(--accent-soft-rgb))]',
    widgetTitle: 'text-sm font-semibold text-[var(--text-primary)]',
    widgetText: 'text-xs leading-5 text-[var(--text-muted)]',
    widgetLink: 'text-[11px] font-medium text-[var(--accent)]',
    widgetBadge: 'inline-flex items-center gap-2 rounded-full border border-rose-500/25 bg-rose-500/8 px-2.5 py-1 text-[11px] text-rose-300',
    widgetMeta: 'text-[11px] text-[var(--text-muted)]',
    timelineHeader: 'flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between',
    timelineLegend: 'flex flex-wrap items-center gap-4 text-sm text-white/65',
    timelineLegendItem: 'inline-flex items-center gap-2',
    timelineLegendNow: 'h-3 w-3 rounded-sm bg-[rgb(var(--accent-rgb))]',
    timelineLegendTarget: 'h-3 w-3 rounded-sm bg-[rgb(var(--accent-soft-rgb))]',
    timelineHint: 'text-sm text-white/55',
    timelineScroll: 'overflow-x-auto',
    timelineGrid: 'grid min-w-[880px] grid-cols-[180px_repeat(4,minmax(120px,1fr))] gap-4',
    timelineCellBase: 'rounded-2xl border border-white/10 bg-white/[0.03] p-4 transition-colors',
    timelineCellInteractive: 'cursor-pointer hover:border-white/20',
    timelineCellActive: 'border-[var(--accent-soft)] bg-[rgba(92,136,255,0.12)]',
    timelineStickyLabel: 'sticky left-0 z-10 flex items-center bg-[rgb(var(--surface-rgb))]',
    timelineSphereLabel: 'text-base font-semibold text-white',
    timelineSphereMeta: 'mt-1 text-sm text-white/55',
    timelineColumnHead: 'sticky top-0 z-10 rounded-2xl border border-white/10 bg-[rgb(var(--surface-rgb))] p-4 text-center',
    timelineColumnDate: 'text-sm font-semibold text-white',
    timelineColumnMeta: 'mt-2 text-sm text-white/55',
    timelineColumnStepWrap: 'mb-4 flex items-center gap-4',
    timelineColumnStepLine: 'h-px flex-1 bg-white/10',
    timelineValueWrap: 'flex items-end justify-between gap-3',
    timelineValue: 'text-xl font-semibold text-white',
    timelineDelta: 'text-sm font-medium text-white/55',
    timelineBarTrack: 'mt-3 h-2 rounded-full bg-white/10',
    timelineBarValue: 'h-full rounded-full',
    timelineDetailsGrid: 'grid gap-4 lg:grid-cols-[minmax(0,1.3fr)_minmax(280px,0.7fr)]',
    timelineDetailsTitle: 'text-base font-semibold text-white',
    timelineDetailsText: 'mt-2 text-sm leading-6 text-white/70',
    timelineActionsList: 'mt-4 space-y-2',
    timelineActionItem: 'flex items-center justify-between gap-3 rounded-2xl border border-white/10 bg-white/[0.03] px-4 py-3',
    timelineActionText: 'text-sm text-white/78',
    timelineActionMeta: 'text-sm text-white/45',
    timelineGoalsList: 'space-y-3',
    timelineGoalItem: 'flex items-start gap-3 border-t border-white/10 pt-3 first:border-t-0 first:pt-0',
    timelineGoalDot: 'mt-1 h-3 w-3 rounded-full',
    timelineGoalText: 'flex-1 text-sm leading-6 text-white/80',
    timelineGoalBadge: 'rounded-full border border-white/10 bg-white/[0.04] px-3 py-1 text-sm text-white/70',
    sphereTone: {
      health: 'bg-emerald-400',
      career: 'bg-blue-500',
      relationships: 'bg-pink-500',
      finance: 'bg-amber-400',
      selfDevelopment: 'bg-teal-400',
      freedom: 'bg-fuchsia-500',
      mind: 'bg-violet-500',
      energy: 'bg-purple-500',
    },
  },
  modal: {
    overlay: 'bg-black/80 backdrop-blur-xl',
    container: 'items-start justify-start px-2 py-2 sm:px-4 sm:py-4 lg:pl-80',
    panel:
      'h-[90vh] w-full max-w-[960px] overflow-hidden rounded-2xl border border-white/10 bg-[var(--surface)] shadow-[var(--shadow-xl)]',
    shell: 'flex h-full flex-col overflow-hidden',
    header:
      'sticky top-0 z-10 flex items-center justify-between gap-4 border-b border-[var(--border-accent)] bg-[var(--surface)] px-4 py-3 sm:px-5',
    headerKicker: 'text-[10px] uppercase tracking-[0.22em] text-[rgb(var(--accent-soft-rgb))]',
    headerTitle: 'truncate text-sm font-medium text-[var(--text-primary)] sm:text-base',
    closeButton:
      'flex h-10 w-10 items-center justify-center rounded-full border border-[var(--border-accent)] bg-white/5 text-lg font-medium leading-none text-[var(--text-primary)] transition-colors hover:bg-white/10',
    body: 'min-h-0 flex-1 overflow-y-auto bg-[var(--surface)] pr-1',
    frameWrap: 'flex min-h-full flex-col px-3 py-3 sm:px-4 sm:py-4',
    frame: 'min-h-[640px] flex-1 rounded-2xl border border-[var(--border-accent)] bg-[var(--surface)]',
    footer:
      'sticky bottom-0 z-10 border-t border-[var(--border-accent)] bg-[var(--surface)] px-4 py-3 sm:px-5',
  },
} as const

export function segmentedTabClass(active: boolean) {
  return cn(
    dashboardDesignSystem.tabs.item,
    active ? dashboardDesignSystem.tabs.itemActive : dashboardDesignSystem.tabs.itemInactive,
  )
}

export function stepIconClass(state: 'done' | 'active' | 'locked') {
  return cn(
    dashboardDesignSystem.step.iconBase,
    state === 'done'
      ? dashboardDesignSystem.step.iconDone
      : state === 'active'
        ? dashboardDesignSystem.step.iconActive
        : dashboardDesignSystem.step.iconLocked,
  )
}

export function stepLabelClass(state: 'done' | 'active' | 'locked') {
  return cn(
    dashboardDesignSystem.typography.subtitle,
    state === 'done'
      ? dashboardDesignSystem.step.labelDone
      : state === 'active'
        ? dashboardDesignSystem.step.labelActive
        : dashboardDesignSystem.step.labelLocked,
  )
}
