import path from 'node:path'

import type { PromptSourceDefinition } from './types.js'

const ROOT_PROMPTS_DIR = path.resolve(process.cwd(), 'prompts')

export const DEFAULT_RUNTIME_PROMPT_SOURCES: PromptSourceDefinition[] = [
  {
    id: 'master-system-prompt',
    version: '1.0.0',
    filePath: path.join(ROOT_PROMPTS_DIR, 'master-system-prompt.md'),
    ownerAgentIds: ['project_manager'],
    canonical: true,
    defaultVersion: true,
  },
  {
    id: 'task-planning-prompt',
    version: '1.0.0',
    filePath: path.join(ROOT_PROMPTS_DIR, 'task-planning-prompt.md'),
    ownerAgentIds: ['task_planning'],
    canonical: true,
    defaultVersion: true,
  },
  {
    id: 'implementation-prompt',
    version: '1.0.0',
    filePath: path.join(ROOT_PROMPTS_DIR, 'implementation-prompt.md'),
    ownerAgentIds: ['implementation'],
    canonical: true,
    defaultVersion: true,
  },
  {
    id: 'code-review-prompt',
    version: '1.0.0',
    filePath: path.join(ROOT_PROMPTS_DIR, 'code-review-prompt.md'),
    ownerAgentIds: ['code_review'],
    canonical: true,
    defaultVersion: true,
  },
  {
    id: 'bug-investigation-prompt',
    version: '1.0.0',
    filePath: path.join(ROOT_PROMPTS_DIR, 'bug-investigation-prompt.md'),
    ownerAgentIds: ['bug_investigation'],
    canonical: true,
    defaultVersion: true,
  },
  {
    id: 'refactoring-prompt',
    version: '1.0.0',
    filePath: path.join(ROOT_PROMPTS_DIR, 'refactoring-prompt.md'),
    ownerAgentIds: ['refactoring'],
    canonical: true,
    defaultVersion: true,
  },
  {
    id: 'release-readiness-prompt',
    version: '1.0.0',
    filePath: path.join(ROOT_PROMPTS_DIR, 'release-readiness-prompt.md'),
    ownerAgentIds: ['release_readiness'],
    canonical: true,
    defaultVersion: true,
  },
  {
    id: 'smoke-test-prompt',
    version: '1.0.0',
    filePath: path.join(ROOT_PROMPTS_DIR, 'smoke-test-prompt.md'),
    ownerAgentIds: ['smoke_test'],
    canonical: true,
    defaultVersion: true,
  },
  {
    id: 'echo-agent-prompt',
    version: '1.0.0',
    filePath: path.join(ROOT_PROMPTS_DIR, 'echo-agent-prompt.md'),
    ownerAgentIds: ['echo_agent'],
    canonical: true,
    defaultVersion: true,
  },
  {
    id: 'summarizer-agent-prompt',
    version: '1.0.0',
    filePath: path.join(ROOT_PROMPTS_DIR, 'summarizer-agent-prompt.md'),
    ownerAgentIds: ['summarizer_agent'],
    canonical: true,
    defaultVersion: true,
  },
  {
    id: 'classification-agent-prompt',
    version: '1.0.0',
    filePath: path.join(ROOT_PROMPTS_DIR, 'classification-agent-prompt.md'),
    ownerAgentIds: ['classification_agent'],
    canonical: true,
    defaultVersion: true,
  },
  {
    id: 'extraction-agent-prompt',
    version: '1.0.0',
    filePath: path.join(ROOT_PROMPTS_DIR, 'extraction-agent-prompt.md'),
    ownerAgentIds: ['extraction_agent'],
    canonical: true,
    defaultVersion: true,
  },
  {
    id: 'planning-agent-prompt',
    version: '1.0.0',
    filePath: path.join(ROOT_PROMPTS_DIR, 'planning-agent-prompt.md'),
    ownerAgentIds: ['planning_agent'],
    canonical: true,
    defaultVersion: true,
  },
  {
    id: 'mentor-agent-prompt',
    version: '1.0.0',
    filePath: path.join(ROOT_PROMPTS_DIR, 'mentor-agent-prompt.md'),
    ownerAgentIds: ['mentor_agent'],
    canonical: true,
    defaultVersion: true,
  },
]
